### ISSUE TITLE
Implement the provider in the extension

### ISSUE THREAD

**Issue by gregoryguillou** [dontpanicdao/starknet-burner#113]
## Objectives
Currently the extension only supports `CallContract` and `GetBlock` for the provider. The goal of the issue is to make sure the whole interface is fully managed.

## Success Criterias
In order for the task to succeed, provider should implement
- [x]  getClassAt
- [x]  getEstimateFee
- [x] getStorageAt
- [x] getTransaction
- [x] getTransactionReceipt
- [x] invokeFunction
- [x] deployContract
- [x] declareContract
- [x] getCode
- [x] waitForTransaction

## Additional Information
N/A

**Comment by 0xJilan** [comment]
Implement in extension and keyring side
