### ISSUE TITLE
An sample application to Starkpill your friends

### ISSUE THREAD

**Issue by gregoryguillou** [dontpanicdao/starknet-burner#55]
## Objectives
create an sample application that use Argent-X and Braavos and we will be able to move to the `burner-wallet`

## Success Criterias
- [x] create a new directory named starkpilled at the root directory of the project that will be based on `Next`
- [x] install `get-starknet` and `starknet` (i.e. starknet.js) with the project
- [x] add some logic to connect to the wallet with `get-starknet`. A very basic example looks like than:

```javascript
import { getStarknet } from 'get-starknet';

export const connect = async () => {
	let starknet = getStarknet();
	console.log('connect...');
	if (!starknet.isConnected) {
		await starknet.enable();
	}
	if (starknet.selectedAddress) {
		const account = starknet.account;
		return account;
	}
	return;
};
```

- [x] Add 2 input fields, one that will content `to` that will be the address to transfer token to; the second will contain `amount` that is a number with default `1` that defines the number of stark pills to send
- [x] Add 3 buttons: (1) `Cancel` with reset the form; (2) `Faucet` will set the `to` to the faucet address, i.e. `0x05a87f6bec0b6121e55f291f8e06e6149accd706fb43c725a7f1fd3f3f62aadf` and (3) `send` will send the token to the address. Note that on goerli, Starkpills are `0x05a87f6bec0b6121e55f291f8e06e6149accd706fb43c725a7f1fd3f3f62aadf`.

```javascript
import { Contract } from 'starknet';
import erc20_abi from 'erc20_abi.json';

const starkpillAddress = `0x05a87f6bec0b6121e55f291f8e06e6149accd706fb43c725a7f1fd3f3f62aadf`;
export const send = async (to: string, amount: number) => {
	let currentAccount = await connect();
	if (!currentAccount) {
		// error
		return;
	}
	const starkpillAddress =
            '0x7a1a9784591aad3cc294ed3d89fa45add74e96e8c20e46a21153a6aa979a9cb';
	let erc20 = new Contract(erc20_abi, starkpillAddress, currentAccount);
	try {
		let tx = await erc20.transfer(to, [amount, 0]);
	} catch (e) {
		// error
		return;
	}
};
```

- [x] (optional) you can check the current network is goerli and display an error if that is not the case
- [x] (optional) you can detect changes in the account/network and display the account in the application.

## Additional informations
- the abi file is localted in `drone/src/abi/erc20_abi.json`

**Comment by 0xJilan** [comment]
Job done !
